CREATE TABLE utenti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  data_creazione TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE utenti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(50) NOT NULL,
  cognome VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL
);

CREATE TABLE gioco (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ruolo VARCHAR(50) NOT NULL,
  ruolo_secondario VARCHAR(50)
);